version: '3'
services:
  server:
    build:
      context: ./backend/
    volumes:
      - ./backend/:/usr/app/backend/
      - /usr/app/backend/node_modules/
    ports:
      - "8626:8626"
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app/client/
      - /usr/app/client/node_modules/
    depends_on:
      - server
    ports:
      - "3000:3000"
